## Useful constants. Generated by generate_sdk_list.py

DEFAULT_VERSION = "1.30.0"

SDK_VERSION_INTEGRITY = {
    "1.28.0": {
        "linux-amd64": "sha512-AAya3CwUC+0/c+KMqr36gtdtfDXEsM+TMi0Py8HyigcJYukoyRMuprYMAu1nenRJz6sLkRNJcUGaIdq2XOV4Hg==",
        "darwin-amd64": "sha512-9MWuOOEzHDK0FsR1Nqo9NeWLm5s4ALXg9G7ISVtOyJHcyZNm3ZqkT4t66yQmnxF/2GcgJ5AnBtiFsb6xq9x3HA==",
        "darwin-arm64": "sha512-DfOdAeV/gXXoboQ/wddd9AKKKIn+t0d9ZSIMEgwEottRGxxKQwPVse80rQwXM8HeF6ZFAomMliWyo1vMoT15eQ=="
    },
    "1.29.4": {
        "linux-amd64": "sha512-rG8P0E0J4GoxeG2/gokfbbRZ54fxLMy2aHBKrRgymvfBp7w7xcSwfE+ln7gxD6weHbEX58Bz3lnY9E+X4vvL+g==",
        "darwin-amd64": "sha512-ljGZDzzV1QIPgH4TY5uqvM2CBRYERzt6W/wUPckgfkwy9vZL5GiT8H0HI81RnDhJlWPcDvRCx4l1M0cPVZ2ANg==",
        "darwin-arm64": "sha512-1GwkBw+YMImgLLHF8b+kLEzMW4UJ5y97rFDXpLRf6i9xEdtWnWWBNzYmZ/8mqItJvG+tHbwQgzQubWQodspquw=="
    },
    "1.30.0": {
        "linux-amd64": "sha512-1Thw4abJs7UDZkiak4f04lTGZJVeky4+JeIIi7Q3snC/q3XSQbUISSM/mjS7Hwi0FWfruB6ik1IQSuD1scueiA==",
        "darwin-amd64": "sha512-5wWzUYkFKICv7+rHJ5eDTSdQv8/Ilx3ZE8wrVXXqciLpz6Prs4peXe7I8GCJ7MZUvq+cT+mQrPQeV3WMJrPWKg==",
        "darwin-arm64": "sha512-SMH6VVXwIfiqNl+qqWsQaATOXjAiFCoqFmvJHs1bItp58BLSDBpJY+AjbfAKIU8zEc3YQt5KsZRCyhyDs7y4WQ=="
    },
    "1.29.3": {
        "linux-amd64": "sha512-aSZ/dlMFQ2MGIhq79jWXwzg64i+4uJPsXbKLEuAM8KaQI26QOMwztHXUbOLJrBLK6HFELaw+ySsMWMIfwNjBuw==",
        "darwin-amd64": "sha512-VmFNUuU0UgsDJXxMVJd+bs5fEt7BNcPkaYN9wG8P8CYgj+Fy0F6bjYZdqkzcAzwshfPX9UfgssOFx0CYlu2bFA==",
        "darwin-arm64": "sha512-5ccgmAUAkV5yD/c7KNi1qWnyaAMNC3+fMCQzfYUpFgrBzj90DmLzftd4QgcBxV8QBqhwU75jn9XzB6KbDp/0ZQ=="
    },
    "1.25.0": {
        "linux-amd64": "sha512-XKVhcpini5WAeO8Qjvw4u3Mpe1PAE1N8xxjqX8D0DjTMz3T7DSgasQacjP0nG3zsHc13/343GiuYvk77akmF8Q==",
        "darwin-amd64": "sha512-ghPvGxYMzsuAz2czS2gthIhjZcKg+YZKF5VtfFaoJESXNkJUzuV6gePOaXo/7usNJ8VRkdy6xU76b5qLSHaczg==",
        "darwin-arm64": "sha512-DuWrohC7BgdF+CxIrZvKbhZqnutoRQGpefo69qdUNe4cTHj4UZZHJOsrEdp5Z9TqfSm+KnxL34UCN9bYgc+i0w=="
    },
    "1.26.0": {
        "linux-amd64": "sha512-EVJ1pGHl+wlRX02HoSsHzN8WYu15qJrwheyWWvGi6d1d3PqTmdoMQJ3im38q7eKdmvbLke64C+u+sJ3Fapqzbw==",
        "darwin-amd64": "sha512-KTYV2V0SwNpHEjyvg4m8wbHXrjIhwjuYvSa5qhDVYIzJx/jVwjo3bL4TaDqxHjAUK678vI+9gWfz+mFdrL9DUA==",
        "darwin-arm64": "sha512-m5dRgN+lD1YuPmMSXQd1KDWGcK86HgntoS7dbPKdjGprHv3MuwciLRjjIBT3pQqcnWbAUDUKM4EVqmW9N9hPQQ=="
    },
    "1.27.1": {
        "linux-amd64": "sha512-YH/8MVWDplSnzm2e4bwM4YuoV1ChP32XLv/iU6U+O7mRD1+wg+uv14AtORkiJkkwE7nIgQjO6qqBkjIwmc96ng==",
        "darwin-amd64": "sha512-ZjmWupVZTC7pe2PkNWhWfUi62LsEWYvCfiPwpkplJdZzvEA4F6e9TfsEP3/rf58x54fnESMYfjU0TMsXF5uSFQ==",
        "darwin-arm64": "sha512-reo9s6ohdHQyUaYYTPrQt0IkBz5hjxnf2AxNAxwTUqGIENZSpcQrEOE9jbheQGedroNEgjjCLu/wS1qs1lMAEQ=="
    },
    "1.29.0": {
        "linux-amd64": "sha512-JWAgq4TubY1VvXol9qu/7v663g2NF818PRw7CKm0hZRU6X9JctroujE4ikxwxcwIKMT/kTCNdtZShqWSWG+/lg==",
        "darwin-amd64": "sha512-4YYHkklgohrXLMdqCvHdB/AntWROJylWSJpuEsfjvLeJp5ESeRVzPM+hfNGk8bfLgZLVckS0KkDKn4pdzpi8MQ==",
        "darwin-arm64": "sha512-J8rI6m/71P9iUZVpeoOs93OmtvC6du9dSvRS864c6Ubx01lEeAweE0C+GeHP7pqUjIyQAnisFxLbQqo9cGO7Sg=="
    },
    "1.26.1": {
        "linux-amd64": "sha512-nds+FydZvmSwdIwNEDqXbf1q7NyqDI//dySom3Qms+AIY7h4Kz3/FvBHaL6eVqy9o3VefHwAVxvDqNEAsl4EsQ==",
        "darwin-amd64": "sha512-xB/50DdjxcCM6HmiBIDZqSVKnn9YEFbPXOz2UhhF8XHgzhfsPOI2lp6eDEzseS3C2bKv1x9mE97RkpiPHhYrgQ==",
        "darwin-arm64": "sha512-4WCmyGO2LDAVgrZjXZ2+pCdQJWOfWJWxH8YbEamYbUAc9WaVro92ANwXxapZAMkNr7XJAPtxZicUWJSO7W32jw=="
    },
    "1.29.1": {
        "linux-amd64": "sha512-7m0BnT8CCd6ixYcVCBN7upuNPe5+ooen3N+lIKyp3mL+Je026b1pPiYzuGrck5RLNFJNJobpos/g4xWasE4vzA==",
        "darwin-amd64": "sha512-xsUGXu9CAjmCMoj+nXGm/s85hzcUnvMrOLpkmysA6/atJmDb0x+SvZKSXLgqk6zHRk4P8DNU9g+4/rKiBAZolQ==",
        "darwin-arm64": "sha512-QCAp3F4VuQM+YEZFcmmqyEX5i4AdrHlZ1eA5DunvlcgiUJT38vPpZm+iv4vsp1mAAwI3ODYUCINlv36oAGgz8w=="
    },
    "1.24.2": {
        "linux-amd64": "sha512-KzMMGAL3/YWKim6XFBsHpCYO7BNXEsiRPTa7jkj42/pFqOWxPBXnwgEnpV11v9pQB78BjoU88VbjrCsBnUkokg==",
        "darwin-amd64": "sha512-jQpzMI2q+7Ze2XRJvOgeCdJJBF1FlM5OQFDMjF8qoxR79KT72mtzoYsKDLpPiKAaTgufZsNx66kk47s2/phg1Q==",
        "darwin-arm64": "sha512-8utXrAeg7rl9ao42vDl+sLW8qkMsyttaV01WhN1ILSEhoZPz398e4EtN983q2NiZxaV+dTKD6kBrrVYAY9urtw=="
    },
    "1.24.1": {
        "linux-amd64": "sha512-v5mod0dDDHNp/P5jY4+aEMO2pFgc/pPexf3VgDbicDYLSLzOuh3FeyQ5upydUNwzAShzcTaJOg7Ztnur2C8wkA==",
        "darwin-amd64": "sha512-0AwKisRdPAutEpSs49hQJoHYTkjH26+3+Ak3HI0uUXF0/Fv3uiPNCysJZYNavpr8J7YXJf/ukMzmEZCT8UKOcw==",
        "darwin-arm64": "sha512-+h38L9blOGn1WICqnrjcRSgVWd6jEHmrbovWpVrQ4ThHfV53ZirK9O2QVDIj4fp/aZ5gek6hMl9+0Yfu2nBH+A=="
    },
    "1.28.3": {
        "linux-amd64": "sha512-23qvrfo8HLXHvYLzdUJbEdZlISlYCsUHsuLikMEBjvGHNzUtUGkDUDodR8wVafBQ3/cboi8GBX96KuMYr9n05Q==",
        "darwin-amd64": "sha512-gY/w+RSTON9sFeQuy4iyR0Wj80CpidinC148lwahLBm0p96HP+t3gCBmXdeXXsm+3beqXpxg3KN4KWIlO1eh2w==",
        "darwin-arm64": "sha512-65rqK23RlrhNi+12uw2otMjp8R3Zbl1yJOvbOmP2GkzOr+IXdMeOVV/DsyUF55c+HPP6nocQNUbgiPfoYSjFxg=="
    },
    "1.23.5": {
        "linux-amd64": "sha512-nJ70CCh3VYwozAuPW+9/INu2J0mGWuU5cTXfXBhdFdWcuxOwcIE+J2Hp3kWylpCWeIVncBSK9e5VpF1BMkbETg==",
        "darwin-amd64": "sha512-ClTe9d7paYZmlOOEAPPa7gUtxh/NuKk6QCqVfp2OKX2TSoLqKpbegMTmpZhYr8etV3pu68QiZ1kzvHYyQ0staQ==",
        "darwin-arm64": "sha512-y0BmbNg9i79GTvmYNdNT180CYiwp/LL9u7y4iAu+ArNb+xBmf7jp3G4AvEq1ByfmzhSGsemEQoZfna68nrWM1g=="
    },
    "1.29.5": {
        "linux-amd64": "sha512-sRGQud1S5HPOV/eAoUX8biJQeUoqn+1NubSxMEPfQ2pfxmwHfx60gIdhdkBmoZNtonZgxi0Cq1klsmTz98r3tQ==",
        "darwin-amd64": "sha512-er6vXA8cK2+iq4/w/9jrG9HbY4JD+o8hg8udvehHRMXouk3WY2tT0SEMbocx3ClBn86xEI+GuHLLPBr6yqKjxA==",
        "darwin-arm64": "sha512-RNMBq65EIbHkQn3kFTtzBaI5IwLf2nkkJjPrDEQCnOYPYHqR2oQSrpbqjvM9X75kLxxacuYMpf+o5gbC7zHwVg=="
    }
}